baseURL = "https://eiskern.com/"
languageCode = "en-us"
title = "YuK Portfolio"
theme = "prologue"

banner_link = "img/banner.jpg"

# theme homepage: https://themes.gohugo.io/prologue/

[params]
    name = "YuK (EisKern)"
    description = "Student"
    copyright = "2019 YuK."

[[params.social]]
    medium = "Twitter"
    icon = "twitter"
    link = "https://twitter.com/EisKern"

[[params.social]]
    medium = "GitHub"
    icon = "github"
    link = "https://github.com/EisKern"

# [[params.social]]
#     medium = "facebook"
#     icon = "facebook"
#     link = "#"

# [[params.social]]
#     medium = "dribbble"
#     icon = "dribbble"
#     link = "#"

# [[params.social]]
#    medium = "email"
#    icon = "envelope"
#    link = "#"

# Portfolio column one

[[params.portfolio1]]
    title = "Qiita"
    alt = ""
    source = "img/qiita-rectangle.png"
    url = "https://qiita.com/EisKern"

[[params.portfolio1]]
    title = "Tech Blog"
    alt = ""
    source = "img/blog-top.png"
    url = "https://www.tech-ek.com"


# Portfolio column two

[[params.portfolio2]]
    title = "Tic Toc Toe"
    alt = ""
    source = "img/tic-toc-toe-top.png"
    url = "https://tic-tac-toe.eiskern.com/"

# Portfolio column 3

[[params.portfolio3]]
    title = "Search Book Cover"
    alt = ""
    source = "img/search-book-cover-top.png"
    url = "https://transparent-book-cover-search.herokuapp.com/"


