author = "YuK"
baseurl = "https://eiskern.com/"
copyright = "YuK"
disqusshortname = ""
googleanalytics = "UA-134055907-5"
title = "YuK Homepage"
theme = "prologue-ek"

languageCode = "en-us"

[params]
    name = "YuK (EisKern)"
    description = "Student"
    avatar = "https://twitter.com/EisKern/photo"
    favicon = ""

# intro(top), about, portfolio, contact
[[params.contents]]
    name = "intro"
    title = "Intro"
    href = "top"
    icon = "fa-home"
    banner = "banner"
    homepage_title = "YuK Homepage"
    description = "Constantly Improving"

# [[params.contents]]
#     name = "about"
#     title = "About Me"
#     href = "about"
#     icon = "fa-user"
#     img = "img/about.jpg"
#     description = ""

[[params.contents]]
    name = "portfolio"
    title = "Portfolio"
    href = "portfolio"
    icon = "fa-th"
    description = "created by YuK."

# [[params.contents]]
#     name = "contact"
#     title = "Contact"
#     href = "contact"
#     icon = "fa-envelope"
#     description = ""


# contents in portfolio
[[params.portfolio]]
    title = "Qiita"
    alt = ""
    source = "img/qiita.png"
    url = "https://qiita.com/EisKern"

[[params.portfolio]]
    title = "Tech Blog"
    alt = ""
    source = "img/blog-top.png"
    url = "https://www.tech-ek.com"

[[params.portfolio]]
    title = "Tic Toc Toe"
    alt = ""
    source = "img/tic-toc-toe-top.png"
    url = "https://tic-tac-toe.eiskern.com/"

[[params.portfolio]]
    title = "Search Book Cover"
    alt = ""
    source = "img/search-book-cover-top.png"
    url = "https://transparent-book-cover-search.herokuapp.com/"

[[params.portfolio]]
    title = "Treasure Hunt in Terminal (Linux)"
    alt = ""
    source = "img/treasure-hunt.png"
    url = ""

[[params.portfolio]]
    title = "Standard App in JavaFX"
    alt = ""
    source = "img/standard-app.png"
    url = ""


[social]
    twitter = "EisKern"
    github = "EisKern"
    facebook = ""
    dribbble = ""
    email = ""
