baseURL = "https://eiskern.com/"
languageCode = "en-us"
title = "YuK Portfolio"
theme = "prologue"

[params]
    name = "YuK"
    description = "Student"
    copyright = "2019 YuK."

[[params.social]]
    medium = "Twitter"
    icon = "twitter"
    link = "https://twitter.com/EisKern"

[[params.social]]
    medium = "GitHub"
    icon = "github"
    link = "https://github.com/EisKern"

# [[params.social]]
#     medium = "facebook"
#     icon = "facebook"
#     link = "#"

# [[params.social]]
#     medium = "dribbble"
#     icon = "dribbble"
#     link = "#"

# [[params.social]]
#    medium = "email"
#    icon = "envelope"
#    link = "#"

# Portfolio column one

[[params.portfolio1]]
    title = "Qiita"
    alt = ""
#     source = "img/pic02.jpg"
    url = "#"

[[params.portfolio1]]
    title = "Tech Blog"
    alt = ""
#     source = "img/pic03.jpg"
    url = "#"


# Portfolio column two

[[params.portfolio2]]
    title = "Tic Toc Toe"
    alt = ""
#     source = "img/pic04.jpg"
    url = "#"

# [[params.portfolio2]]
#     title = "Natoque Vitae"
#     alt = ""
#     source = "img/pic05.jpg"
#     url = "#"


# Portfolio column 3

[[params.portfolio3]]
    title = "Search Book Cover"
    alt = ""
#     source = "img/pic06.jpg"
    url = "#"

# [[params.portfolio3]]
#     title = "Orci Convallis"
#     alt = ""
#     source = "img/pic07.jpg"
#     url = "#"

